#1.1
SELECT ARTISTA, TITULO FROM ULTIMOS_LANZAMIENTOS
WHERE ANO = (SELECT MAX(ANO) FROM ULTIMOS_LANZAMIENTOS)
ORDER BY ARTISTA, TITULO;

#1.2
SELECT TITULO FROM TOP_SPOTIFY
WHERE ARTISTA = 'LADY GAGA' AND PERMANENCIA = (SELECT MAX(PERMANENCIA) FROM TOP_SPOTIFY)
ORDER BY TITULO;

#1.3
SELECT TITULO, ARTISTA,
CASE
WHEN GENERO LIKE '%POP%' THEN 'POP'
WHEN GENERO LIKE '%ELECTRO%' OR GENERO LIKE '%HOUSE%' THEN 'ELECTRÓNICA'
ELSE 'OTRO'
END AS TIPO
FROM TOP_SPOTIFY
ORDER BY ARTISTA, TITULO;

