#3.1
CREATE TABLE EMPLEADOS_ANTERIORES
SELECT * FROM EMPLEADOS
WHERE APELLIDO IN ('THOMAS', 'PEREIRA', 'DEVO');
DELETE FROM EMPLEADOS
WHERE APELLIDO IN ('THOMAS', 'PEREIRA', 'DEVO');

#3.2
INSERT INTO EMPLEADOS_ANTERIORES (EMPLEADO_ID, NOMBRE, APELLIDO, PUESTO_ID, EDITORIAL_ID, FECHA_INGRESO, PERMANENCIA)
SELECT EMPLEADO_ID, NOMBRE, APELLIDO, PUESTO_ID, EDITORIAL_ID, FECHA_INGRESO, PERMANENCIA
FROM EMPLEADOS
WHERE APELLIDO = 'CRUZ';
DELETE FROM EMPLEADOS
WHERE APELLIDO = 'CRUZ';
